### PR TITLE
Continuous Malware Analysis functionality added to MalwareAnalysis Module

### PR DESCRIPTION
**Pull request by DigvijayBhosale1729**
## Status
**READY**

## Description
- Continuous Malware Detection 
1. Scan filesystem for files modified in last 1 hour
2. Find probable malicious extensions
3. Find extensions linked to past DJVU Ransomware
4. Scan selected files for Malware

## Todos
- [ ] Tests - Successful Tests run on my own Ubuntu image. Successful on clean Ubuntu image as well
- [ ] Documentation - No documentation updated

## Deploy Notes
- MalwareAnalysis.py in base repo updated for passing single argument ```filename``` instead of file object.
- Updated fileAnalysis, malwareAnalysis to receive singular argument ```filename``` instead of 2 arguments - filename and file object.
- Updated malwareAnalysis.py and malwareAnalysisJSONDisplay.py for threat analysis
- Created continuous_malware_defence.py

## Steps to Test or Reproduce
Run MalwareAnalysis.py by ```python3 MalwareAnalysis.py```

## Impacted Areas in Application
Files changed = 5
MalwareAnalysis.py 
securetea/lib/malware_analysis/continuous_malware_defence.py 
securetea/lib/malware_analysis/fileAnalysis.py
securetea/lib/malware_analysis/malwareAnalysis.py
securetea/lib/malware_analysis/malwareAnalysisJSONDisplay.py

### CODE REVIEW

**Comment by adeyosemanputra** [comment]
@DigvijayBhosale1729 have you try running with travis ci and build without error also can you show the new feature running successfully with video?

**Comment by DigvijayBhosale1729** [comment]
Will upload video within 1-3 days. I'll also try to do on Travis ci. Currently working on Multi Threading and Adding some new features.

**Comment by adeyosemanputra** [comment]
@DigvijayBhosale1729 cool waiting then

**Comment by DigvijayBhosale1729** [comment]
Hello @adeyosemanputra 
Added some nice touches and made the video you requested.

The 2 .exe files, 2 djvu extension files and cat.jpg were maually added by to demonstrate how the script works. Important timestamps are in the video's description box. [Here's](https://www.youtube.com/watch?v=koSosmgkU5g) the video. 

Any suggestions regarding this module or adding a new module are appreciated.

Hope you like it !

**Comment by pwned-17** [comment]
@DigvijayBhosale1729 is it possible for you to use the SecureTea argument helper to get arguments for your Malware Analysis module? 
Instead of getting arguments from the module itself ,can you try to get it through Securetea . 
For help with the arguments parser redder developer guide .

**Comment by DigvijayBhosale1729** [comment]
@pwned-17 I wanted to implement this. I'm relatively new to open source projects, so for fear of breaking the existing program, i haven't done that yet. 
I think with some help, it could be done. Could you guide me on how i should go about it?

**Comment by pwned-17** [comment]
> @pwned-17 I wanted to implement this. I'm relatively new to open source projects, so for fear of breaking the existing program, i haven't done that yet.
> I think with some help, it could be done. Could you guide me on how i should go about it?

Sure I can help you set up the args parser for the same !!

**Comment by pwned-17** [comment]
@DigvijayBhosale1729  
Can you provide all the inputs required, for the malware analyzer, so I can guide you through the process !!

**Comment by DigvijayBhosale1729** [comment]
@pwned-17 Sorry for the late reply.
Inputs are as follows - (Flowchart image at end)
Takes input for continuous malware analysis or single file analysis.

In case of continuous, no further input is required. The script runs on its own.

In case of Single file, the following inputs are taken-
File to be scanned

After this is entered, 4 inputs are taken - 
f/F - Steganographic File Analysis of Suspicious file
m/M - Malware Analysis of Suspicious file
a/A - Steg and Malware analysis
q/Q - Quit
In case of f/F the following inputs are taken
f/F File Information
s/S View Strings
e/E Extract Embedded Data
i/I Run Steg Tools Individually
q/Q Quit

For i/I, the following inputs are taken
Enter tool to use on file
f/F or file
s/S or strings
e/E or exiftool
o/O or foremost
b/B or binwalk
p/P or pngcheck
t/T or steghide
u/U or stegosuite
q/quit/exit for exiting

At any stage, after quitting another input is taken
Use same file? (Y/n)

Flowchart
WhatsApp Image 2021-08-25 at 8 35 23 AM

**Comment by pwned-17** [comment]
@DigvijayBhosale1729  The flow chart was really useful ! I actually thought of doing something like this 

The initial Inputs would be 
- Continuous or Individual File 
If individual file then we take serious of inputs 
    - malware (Boolean value)
    - Steganography (Boolean value)
    - both ( Boolean Value ) 

- If Steganography is true : Then we take these inputs 
     - file info( Boolean)
     - strings(Boolean)
     - exif data(Boolean) 

Under docs reffer  developer guide , in that look into takeinput decarator ! 
To understand how input flow works ,
You can reffer these areas of the code 
- under args directory  look into args-helper.py

**Comment by DigvijayBhosale1729** [comment]
Hello
I've been trying to figure out how the args input works and incorporate malware analysis into it
When i try to take input it gives error in args_handler
```
 python3 SecureTea.py --malware_analysis
WARNING: [bgp.py] use_2_bytes_asn: True
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
ARGSNamespace(HTTP_request_action=None, HTTP_response_action=None, antivirus=False, apache=False, auto_delete=None, auto_server_patcher=False, aws_access_key=None, aws_email=None, aws_secret_key=None, aws_ses=False, clamav=False, conf=None, custom_scan=None, debug=False, dest_port_action=None, dest_port_list=None, dns_action=None, dns_list=None, eligibility_threshold=None, firewall=False, gmail=False, hist=False, ids=False, inbound_IP_action=None, inbound_IP_list=None, insecure_headers=False, interface=None, iot_checker=False, iot_mode=False, ip=None, ip_list=None, listenIp=None, listenPort=None, log_file=None, log_type=None, login=False, malware_analysis=True, mode=None, monitor_file_changes=None, monitor_usb=None, outbound_IP_action=None, outbound_IP_list=None, password=None, path=None, protocol_action=None, protocol_list=None, scan_action=None, scan_list=None, sender_email=None, server_log=False, server_mode=False, server_name=None, severity_factor=None, shodan_api_key=None, skip_config_file=False, skip_input=False, slack=False, slack_token=None, slack_user_id=None, social_eng_email=None, source_port_action=None, source_port_list=None, ssh=False, ssl=False, status_code=None, sysctl=False, system_log=False, system_mode=False, telegram=False, telegram_bot_token=None, telegram_user_id=None, threshold=None, time_lb=None, time_ub=None, to_email=None, twilio_from=None, twilio_sid=None, twilio_sms=False, twilio_to=None, twilio_token=None, twitter=False, twitter_access_token=None, twitter_access_token_secret=None, twitter_api_key=None, twitter_api_secret_key=None, update=None, url=None, virustotal_api_key=False, waf=False, web_deface=False, whatsapp=False, whatsapp_from=None, whatsapp_sid=None, whatsapp_to=None, whatsapp_token=None, window=None, yara=False)

[!] Enter (S/s) to skip...
>> Enter Do you want to run full interactive: test
>> Enter name of file to be scanned: test
>> Enter Enter scan type (1 for Malware scan, 0 for Steganography scan): test
>> Enter virustotal api key: testkey
None
None
None
Traceback (most recent call last):
  File "SecureTea.py", line 19, in <module>
    secT = SecureTea()
  File "/home/SecureTea-Project/securetea/core.py", line 85, in __init__
    args_dict = argsHelper.check_args()
  File "/home/SecureTea-Project/securetea/args/args_helper.py", line 1078, in check_args
    if (self.args.listenIp or self.args.listenPort or self.args.mode or self.args.hostMap):
AttributeError: 'Namespace' object has no attribute 'hostMap'
```
I tried putting a try except block but it didn't work.
Could i get some help?

**Comment by pwned-17** [comment]
@DigvijayBhosale1729  

Seems like you need to check whether the arguments.py has a `hostMap` argument added to the parser.
I have attached my Namespace and you can see that it contains `hostMap=None` whereas your Namespace doesn't have that argument. Kindly check if the hostMap is added to the arguments.py 

image

**Comment by DigvijayBhosale1729** [comment]
GM @pwned-17 
Fixed the issue. Now i'm able to take inputs.
I'd like to ask where the actual program for the module should run.
I think this is the place - 
```
        if self.malware_analysis_provided:
            print('if self.malware_analysis_provided')
```
If that is correct, should i make a file in ```securetea/lib/notifs/secureteaMalwareAnalysis``` and have the main code run there?

**Comment by DigvijayBhosale1729** [comment]
Good evening @pwned-17 @prince-7.
I finally understood how the args helper works and plan to do these changes to solve the issues raised.
- Run input for malware analysis module through Securetea with the option of full interactive mode.
- Shortcut to Malware Analysis module will be ```-malware_analysis```
- Each user uses their own API key preventing unnecessary load on a single API key (In case of multiple users) and eliminating the problem of hard-coding API Keys altogether.
- I think modifications in the current branch wont cut it as it would result in a lot of confusion. Hence I'll be creating a new branch where MalwareAnalysis runs through ```SecureTea.py```. This resolves the problem of too many commits crowding the commit history.

With that being said, I'll delete this PR and create a new one with (hopefullty XD) no issues.

**Pull request closed without merging**
