### PR TITLE
Added integration_list for roadmap.

### PR DESCRIPTION
**Pull request by sunn-e**
## Status
**READY/**

## Description
As per discussion, here is the raw list. Will add web links soon.

## Todos
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by abhisharma404** [comment]
@sunn-e Is there an API or bot for every integration that you have added in this list?

**Comment by sunn-e** [comment]
@abhisharma404 Yes. I did not get into too much detail, primary Google searches led me to their developers page and ways to integrate them. That should suffice. And already stated, this is a raw list. 😃

**Comment by sunn-e** [comment]
Hey @abhisharma404 , I've added few links. Those will be just starting points for someone who might be interested into integrating them. And anyone can update them from time to time so no worries. about that  Some of the API's pages I could not find because of language barrier( Mandarin translated by Google translate wasn't sufficient..sigh) and one of them does not provide API for time being but I believe that they will do it pretty soon(It's Dust messenger, pretty cool in concept). I'll update it once available.

**Comment by sunn-e** [comment]
@rejarehim I can surely do that. But what shall be my criteria?  Should I prioritize the services solely based on number of users? That may lead to only English dominating services getting place in the list. I'm planning on adding two columns as to number of users and region for which it belongs. That way we could go region by region and monthly active user base wise too. Will this be okay? What do you think @adeyosemanputra @abhisharma404

**Comment by abhisharma404** [comment]
@sunn-e Based on their popularity seems a good method to prioritize them.

**Comment by sunn-e** [comment]
@abhisharma404  I just updated the file with MAU stats. Check out PR #83 . There are really interesting services that are very popular and yet to integrated. We all can give them a try one by one this summer.

**Pull request merged**
