### PR TITLE
Detection of malicious devices

### PR DESCRIPTION
**Pull request by jay13patel**
## Status
**READY**

## Description
Detection of malicious devices

## Related PRs
List related PRs against other branches:

branch | PR
------ | ------
other_pr_production | [link]()
other_pr_master | [link]()

## Todos
- [x] Tests
- [x] Documentation

## Deploy Notes
None

## Steps to Test or Reproduce
Using CLI

sudo python setup.py install
pip install -r requirements.txt
sudo python SecureTea.py

Using interactive setup

sudo python setup.py install
pip install -r requirements.txt
sudo python SecureTea.py

```sh
git pull --prune
git checkout <feature-branch>
```

## Impacted Areas in Application
List general components of the application that this PR will affect:

*  SecureTea.py
*  requirements.txt
*  core.py

### CODE REVIEW

**Comment by abhisharma404** [comment]
@jay13patel I genuinely appreciate the hard work you have put into this, but can you take a moment to go through the following points:
- **Using multi threading** - SQLite objects are by default single threaded, that means when you are creating an SQLite object in the main thread, you can't use it with another thread, threads communicate using pipes, however you can use a simple tweak: `check_same_thread=False`
Read here: https://www.sqlite.org/threadsafe.html
- **PEP - 8 conventions:** Make sure your code are PEP-8 formatted, no unnecessary spaces & lines between two code units. Also a 1 line gap between functions of a class & 2 lines otherwise.
- **Add documentation** - However simple the function may be, we may forget it, add a docstring.
- **Respect the DRY principle**, Do Not Repeat Yourself : Please make sure the code is not repeating unnecessarily, here for example the code part of sending notification is repeating twice, why not a function?
- Can you please move it a separate folder under `lib`, we don't want to crowd `core.py`
- Also can you please share your IDE details, I'm not sure but I can roughly guess the indentation that you are using is not 4 spaces, this can give error to many users.

Again I'm no expert, these are some of my suggestions as a contributor, I guess we can help to improve SecureTea code base quality even more. :)
Anyway! this is a great PR :)
Regards

**Comment by rejahrehim** [comment]
@jay13patel As @abhisharma404 Suggested better share your IDE details in our chat group. Better we can use same IDE with same configs
Also, Check my pinned message in the chat group.

**Comment by jay13patel** [comment]
@abhisharma404 thank you for your suggestions . I will keep this in my mind when i will do my next pr. @rejahrehim sure i will share my IDE details

**Comment by rejahrehim** [comment]
@abhisharma404 Please check this and close.

**Comment by abhisharma404** [comment]
@rejahrehim We can close this, it's already been implemented. Also, I do not have the permissions to close it. :)

**Pull request closed without merging**
