### PR TITLE
Creating a hindi README file for Indian users.

### PR DESCRIPTION
**Pull request by sunn-e**
I will keep updating this file with the help of other Indian devs.

## Status
**IN DEVELOPMENT**

## Description
I think it's nice to have a Hindi README file for Indian users. This will increase the reach of the project.

## Todos
- [x] Documentation

### CODE REVIEW

**Comment by sunn-e** [comment]
@rejahrehim I added some content. More is on the way.

**Comment by sunn-e** [comment]
Is it normal to have this many codacy-bot comments? Am I doing anything wrong?

**Comment by rejahrehim** [comment]
> Is it normal to have this many codacy-bot comments? Am I doing anything wrong?

Try to fix those comments.

**Comment by sunn-e** [comment]
@rejahrehim  Why codacy bot is giving so many warnings. I simply took the README.md file and put my translated words in it. Nothing changed. Please guide me on this one. I feel frustrated now.

**Pull request closed without merging**
