### PR TITLE
Prerequisites corrected for all APT manager based systems

### PR DESCRIPTION
**Pull request by DigvijayBhosale1729**
## Status
**READY**

## Description
1. Improved prerequisites for clean and smooth installation on any APT package manager based OS.
2. Added missing module uvloop to ```requirements.txt```

## Todos
- [ ] Tests - Tested on clean Ubuntu 20.04 using docker. Tested multiple times with zip install and git clone method.
- [ ] Documentation - Documentation appropriately changed. Redundant statements have been removed, and comments added to the edited files for easy future development

## Deploy Notes
- Python3, Python3-pip (pip3) and git are reinstalled
- Added missing module uvloop to ```requirements.txt``` 

## Steps to Test or Reproduce
- This was a PR addressing issue #301 
- Issue used to arise when a new system, possibly a VM or a docker image didn't have python3-pip installed and git. Without git, netfilterqueue isnt installed and this somehow ends up blocking the pip install as well.
- Even in cases where git is installed, the requirements.txt had to be rerun. Repeating the statement in the installer facilitates clean installation.

## Impacted Areas in Application
Files affected
install_dependencies_apt.sh
requirements.txt
README.md
docs/en-US/user-guide.md

### CODE REVIEW

**Comment by DigvijayBhosale1729** [comment]
Additionally, I also improved the docs.

**Comment by adeyosemanputra** [comment]
it' conflicts, have you recheck again @DigvijayBhosale1729 ?

**Comment by DigvijayBhosale1729** [comment]
Resolved conflicts.
Number of conflicts = 1
Conflicts resolved = 1
File where conflict occured = user-guide.md
Line = 975
Description = Improved Grammar.
Conflicting Statement -
It simply represents the number of times you want to ignore the possibility of an attack. In other words, it is the extent to which IDS will not bother to inform you about the attack. Once it crosses the limit (here threshold), it will start notifying you about the possible attack. The lower the number is, the more sensitive IDS is, and may also give rise to false alarms. The higher the number is, the less sensitive IDS is, it may give rise to less false positives but at the same time choosing a very high number is not suggested either. Choose a mid range number within (10-100) to be on the safer side while keeping alarms of false positives to the minimal.
@adeyosemanputra

**Comment by adeyosemanputra** [comment]
@DigvijayBhosale1729 can you share your screenshot when securetea running  in your local machine after your make change it?

**Review by adeyosemanputra — APPROVED** [review]

**Review by adeyosemanputra — APPROVED** [review]

**Review by adeyosemanputra — APPROVED** [review]

**Comment by adeyosemanputra** [comment]
@all-contributors please add @DigvijayBhosale1729  for code

**Comment by DigvijayBhosale1729** [comment]
@adeyosemanputra, here are the screenshots you requested
I'm using a Ubuntu Image.

The Image is clean, i.e. nothing other than base OS is present.

Started with installing ```wget``` and ```unzip``` to Download SecureTea Repository as a .zip package, unzip and install it.
Can also use git clone to Download Repository as a Folder. This would require installation of ```git``` instead of ```wget``` and ```unzip```

basic_install
zip

After Unzipping and changing directories to ```SecureTea-Project-master```, prerequisites are installed by using command ```bash install_dependencies_apt.sh```

install_dep

Image is clean, hence software-properties-common is installed. Geographic area and Timezone needs to be entered.

dattime

After installing prerequisites successfully (this might take 3-5 mins if distro is clean and less if some of the dep are preinstalled) , securetea is installed by using command ```python3 setup.py install```

setup_success

*Note - In case of previous installer, this step would not be completed.*

*Reason - Packages wouldnt be installed because netfilterqueue installation failed before installation script could be finish running.* 

After securetea is installed, it can be run with command ```securetea``` in terminal

securetea_success

*Note - In case of previous installer, this command used to give uvloop module missing error along with many other module missing errors. This happened because of 2 reasons. uvloop wasn't included in ```requirements.txt``` and dependency installer broke because netfilterqueue installation through pip is unstable and often fails while building wheel. Installation via git and apt is reliable*

**Pull request merged**
